### ISSUE TITLE
filter broken UwU

### ISSUE THREAD

**Issue by crazygmr101** [starstruck-bot/StarStruck#7]

**Comment by crazygmr101** [comment]
This looks to be the filter expecting a space or otherwise character on both ends.

**Comment by Naia-love** [comment]
oop

**Comment by crazygmr101** [comment]
Still broken. I need to look into how the regexes work a little bit. I can't just do https://github.com/starstruck-bot/StarStruck/commit/b2f066f9bdeac76ab91070f619fee236ba238b7e because it'd filter things like sma*sh it*. Maybe force a space on either side? Or other characters? 
@Naia-love any ideas?

**Comment by Naia-love** [comment]
hmm. instead of using regex. you could just check if the message have x or y word. i mean, on another bot i know (in js) it just try an includes of an array of banned word. and if one is detected. well it'll return true. So yeah its not as powerfull as a regex where you could even detect censored word. but it do the job
